package constants

// Item name to spritesheet location. Item numbers, not pixels. x grows right, y grows down
var SpriteLocations = map[string]struct{ X, Y int }{
	PalmFruit:        {14, 28},
	Apple:            {7, 28},
	Wildberry:        {8, 28},
	HylianMushroom:   {4, 29},
	HyruleHerb:       {25, 29},
	HylianBass:       {30, 27},
	SankeCarp:        {6, 28},
	RawGourmetMeat:   {36, 28},
	RawWholeBird:     {37, 28},
	RawPrimeMeat:     {33, 28},
	RawBirdThigh:     {35, 28},
	RawMeat:          {34, 28},
	RawBirdDrumstick: {34, 28},

	BirdEgg:          {26, 28},
	FreshMilk:        {27, 28},
	Acorn:            {18, 28},
	ChickalooTreeNut: {19, 28},
	HylianRice:       {25, 28},
	TabanthaWheat:    {30, 28},
	CaneSugar:        {23, 28},
	GoatButter:       {29, 28},
	GoronSpice:       {24, 28},
	RockSalt:         {22, 29},
	MonsterExtract:   {31, 28},

	HeartyTruffle:        {5, 29},
	HeartyBass:           {31, 27},
	HeartyRadish:         {26, 29},
	HeartyBlueshellSnail: {1, 28},
	HeartyDurian:         {10, 28},
	BigHeartyTruffle:     {11, 29},
	HeartySalmon:         {38, 27},
	HeartyLizard:         {12, 0},
	BigHeartyRadish:      {27, 29},

	StamellaMushroom:     {0, 29},
	RestlessCricket:      {9, 0},
	CourserBeeHoney:      {15, 21},
	BrightEyedCrab:       {22, 28},
	StaminokaBass:        {2, 28},
	EnergeticRhinoBeetle: {2, 0},

	EnduraShroom: {13, 29},
	TirelessFrog: {4, 0},
	EnduraCarrot: {37, 29},

	SpicyPepper:         {16, 28},
	WarmSafflina:        {29, 29},
	SummerwingButterfly: {16, 0},
	Sunshroom:           {2, 29},
	WarmDarner:          {19, 0},
	SizzlefinTrout:      {0, 28},

	Hydromelon:          {13, 28},
	CoolSafflina:        {28, 29},
	WinterwingButterfly: {13, 0},
	Chillshroom:         {1, 29},
	ColdDarner:          {5, 0},
	ChillfinTrout:       {32, 27},

	Voltfruit:            {21, 28},
	ElectricSafflina:     {34, 29},
	ThunderwingButterfly: {17, 0},
	Zapshroom:            {7, 29},
	ElectricDarner:       {10, 0},
	VoltfinTrout:         {33, 27},

	FireproofLizard:      {20, 0},
	SmotherwingButterfly: {3, 0},

	Rushroom:        {38, 28},
	SwiftCarrot:     {35, 29},
	HightailLizard:  {18, 0},
	FleetLotusSeeds: {12, 28},
	SwiftViolet:     {36, 29},
	HotFootedFrog:   {1, 0},

	BlueNightshade:   {32, 29},
	SneakyRiverSnail: {4, 28},
	SunsetFirefly:    {6, 0},
	SilentShroom:     {8, 29},
	StealthfinTrout:  {5, 28},
	SilentPrincess:   {33, 29},

	MightyThistle:     {30, 29},
	BladedRhinoBeetle: {8, 0},
	MightyBananas:     {15, 28},
	Razorshroom:       {9, 29},
	MightyCarp:        {34, 27},
	RazorclawCrab:     {20, 28},
	MightyPorgy:       {35, 27},

	Armoranth:         {31, 29},
	RuggedRhinoBeetle: {15, 0},
	FortifiedPumpkin:  {17, 28},
	Ironshroom:        {10, 29},
	ArmoredCarp:       {37, 27},
	IronshellCrab:     {21, 28},
	ArmoredPorgy:      {36, 27},

	BokoblinHorn:    {18, 26},
	MoblinHorn:      {24, 26},
	LizalfosHorn:    {21, 26},
	LynelHorn:       {27, 26},
	HinoxToenail:    {6, 27},
	KeeseWing:       {33, 26},
	ChuchuJelly:     {11, 27},
	OctorokTentacle: {35, 26},
	OctoBalloon:     {28, 27},
	AncientScrew:    {1, 27},
	AncientSpring:   {2, 27},

	BokoblinFang:  {19, 26},
	MoblinFang:    {25, 26},
	LizalfosTalon: {22, 26},
	// LynelHoof:         {},
	// HinoxTooth:        {},
	// MoldugaFin:        {},
	// WhiteChuchuJelly:  {},
	// RedChuchuJelly:    {},
	// YellowChuchuJelly: {},
	// OctorokEyeball:    {},
	// IceKeeseWing:      {},
	// FireKeeseWing:     {},
	// ElectricKeeseWing: {},
	// AncientGear:       {},
	// AncientShaft:      {},

	// BokoblinGuts:       {},
	// MoblinGuts:         {},
	// LizalfosTail:       {},
	// LynelGuts:          {},
	// HinoxGuts:          {},
	// MoldugaGuts:        {},
	// KeeseEyeball:       {},
	// IcyLizalfosTail:    {},
	// RedLizalfosTail:    {},
	// YellowLizalfosTail: {},
	// AncientCore:        {},
	// GiantAncientCore:   {},

	// DinraalsScale: {},
	// NyadrasScale:  {},
	// FaroshsScale:  {},

	// DinraalsClaw: {},
	// NyadrasClaw:  {},
	// FaroshsClaw:  {},

	// ShardofDinraalsFang: {},
	// ShardofNyadrasFang:  {},
	// ShardofFaroshsFang:  {},

	// ShardofDinraalsHorn: {},
	// ShardofNyadrasHorn:  {},
	// ShardofFaroshsHorn:  {},

	// StarFragment: {},
	// Fairy:        {7, 0},

	// Diamond:       {},
	// Ruby:          {},
	// Sapphire:      {},
	// Topaz:         {},
	// Opal:          {},
	// Amber:         {},
	// LuminousStone: {},
	// Flint:         {},
	// Wood:          {},

	DubiousFood:    {11, 26},
	SimmeredFruits: {15, 23},
	RockHardFood:   {12, 26},
}
