
export var Names = {
	 Acorn: "Acorn",
	 Amber: "Amber",
	 AncientCore: "Ancient Core",
	 AncientGear: "Ancient Gear",
	 AncientScrew: "Ancient Screw",
	 AncientShaft: "Ancient Shaft",
	 AncientSpring: "Ancient Spring",
	 Apple: "Apple",
	 ApplePie: "Apple Pie",
	 Armoranth: "Armoranth",
	 ArmoredCarp: "Armored Carp",
	 ArmoredPorgy: "Armored Porgy",
	 BakedApple: "Baked Apple",
	 BakedFortifiedPumpkin: "Baked Fortified Pumpkin",
	 BakedPalmFruit: "Baked Palm Fruit",
	 BigHeartyRadish: "Big Hearty Radish",
	 BigHeartyTruffle: "Big Hearty Truffle",
	 BigHeartyTrufflex0: "Big Hearty Truffle x0",
	 BirdEgg: "Bird Egg",
	 BlackenedCrab: "Blackened Crab",
	 BladedRhinoBeetle: "Bladed Rhino Beetle",
	 BlueNightshade: "Blue Nightshade",
	 BlueshellEscargot: "Blueshell Escargot",
	 BokoblinFang: "Bokoblin Fang",
	 BokoblinGuts: "Bokoblin Guts",
	 BokoblinHorn: "Bokoblin Horn",
	 BrightEyedCrab: "Bright-Eyed Crab",
	 CampfireEgg: "Campfire Egg",
	 CaneSugar: "Cane Sugar",
	 CarrotCake: "Carrot Cake",
	 CarrotStew: "Carrot Stew",
	 CharredPepper: "Charred Pepper",
	 ChickalooTreeNut: "Chickaloo Tree Nut",
	 ChillfinTrout: "Chillfin Trout",
	 Chillshroom: "Chillshroom",
	 ChuchuJelly: "Chuchu Jelly",
	 ClamChowder: "Clam Chowder",
	 ColdDarner: "Cold Darner",
	 CoolSafflina: "Cool Safflina",
	 CopiousFriedWildGreens: "Copious Fried Wild Greens",
	 CopiousMeatSkewers: "Copious Meat Skewers",
	 CopiousMushroomSkewers: "Copious Mushroom Skewers",
	 CopiousSeafoodSkewers: "Copious Seafood Skewers",
	 CopiousSimmeredFruits: "Copious Simmered Fruits",
	 CourserBeeHoney: "Courser Bee Honey",
	 CrabOmeletwithRice: "Crab Omelet with Rice",
	 CrabRisotto: "Crab Risotto",
	 CrabStirFry: "Crab Stir-Fry",
	 CreamofMushroomSoup: "Cream of Mushroom Soup",
	 CreamofVegetableSoup: "Cream of Vegetable Soup",
	 CreamyHeartSoup: "Creamy Heart Soup",
	 CreamyMeatSoup: "Creamy Meat Soup",
	 CreamySeafoodSoup: "Creamy Seafood Soup",
	 CurryPilaf: "Curry Pilaf",
	 CurryRice: "Curry Rice",
	 Diamantx0: "Diamant x0",
	 Diamond: "Diamond",
	 DinraalsClaw: "Dinraal's Claw",
	 DinraalsScale: "Dinraal's Scale",
	 DubiousFood: "Dubious Food",
	 EggPudding: "Egg Pudding",
	 EggTart: "Egg Tart",
	 ElectricDarner: "Electric Darner",
	 ElectricKeeseWing: "Electric Keese Wing",
	 ElectricSafflina: "Electric Safflina",
	 Elixir: "Elixir",
	 EnduraCarrot: "Endura Carrot",
	 EnduraShroom: "Endura Shroom",
	 EnergeticRhinoBeetle: "Energetic Rhino Beetle",
	 Fairy: "Fairy",
	 FairyTonic: "Fairy Tonic",
	 FaroshsClaw: "Farosh's Claw",
	 FaroshsScale: "Farosh's Scale",
	 FireKeeseWing: "Fire Keese Wing",
	 FireproofLizard: "Fireproof Lizard",
	 FishPie: "Fish Pie",
	 FishSkewer: "Fish Skewer",
	 FishandMushroomSkewer: "Fish and Mushroom Skewer",
	 FleetLotusSeeds: "Fleet-Lotus Seeds",
	 Flint: "Flint",
	 FortifiedPumpkin: "Fortified Pumpkin",
	 FragrantMushroomSauté: "Fragrant Mushroom Sauté",
	 FreshMilk: "Fresh Milk",
	 FriedBananas: "Fried Bananas",
	 FriedEggandRice: "Fried Egg and Rice",
	 FriedWildGreens: "Fried Wild Greens",
	 FrozenBass: "Frozen Bass",
	 FrozenBirdDrumstick: "Frozen Bird Drumstick",
	 FrozenBirdThigh: "Frozen Bird Thigh",
	 FrozenCarp: "Frozen Carp",
	 FrozenCrab: "Frozen Crab",
	 FrozenHeartyBass: "Frozen Hearty Bass",
	 FrozenHeartySalmon: "Frozen Hearty Salmon",
	 FrozenPorgy: "Frozen Porgy",
	 FrozenRiverSnail: "Frozen River Snail",
	 FrozenTrout: "Frozen Trout",
	 FrozenWholeBird: "Frozen Whole Bird",
	 FruitPie: "Fruit Pie",
	 FruitandMushroomMix: "Fruit and Mushroom Mix",
	 Fruitcake: "Fruitcake",
	 GiantAncientCore: "Giant Ancient Core",
	 GlazedMeat: "Glazed Meat",
	 GlazedMushroom: "Glazed Mushroom",
	 GlazedSeafood: "Glazed Seafood",
	 GlazedVeggies: "Glazed Veggies",
	 GoatButter: "Goat Butter",
	 GoronSpice: "Goron Spice",
	 GourmetMeatCurry: "Gourmet Meat Curry",
	 GourmetMeatStew: "Gourmet Meat Stew",
	 GourmetMeatandRiceBowl: "Gourmet Meat and Rice Bowl",
	 GourmetMeatandSeafoodFry: "Gourmet Meat and Seafood Fry",
	 GourmetPoultryCurry: "Gourmet Poultry Curry",
	 GourmetPoultryPilaf: "Gourmet Poultry Pilaf",
	 GourmetSpicedMeatSkewer: "Gourmet Spiced Meat Skewer",
	 HardBoiledEgg: "Hard-Boiled Egg",
	 HeartyBass: "Hearty Bass",
	 HeartyBlueshellSnail: "Hearty Blueshell Snail",
	 HeartyDurian: "Hearty Durian",
	 HeartyLizard: "Hearty Lizard",
	 HeartyRadish: "Hearty Radish",
	 HeartySalmon: "Hearty Salmon",
	 HeartyTruffle: "Hearty Truffle",
	 HeartyTrufflex0: "Hearty Truffle x0",
	 HerbSauté: "Herb Sauté",
	 HightailLizard: "Hightail Lizard",
	 HinoxGuts: "Hinox Guts",
	 HinoxToenail: "Hinox Toenail",
	 HinoxTooth: "Hinox Tooth",
	 HoneyCandy: "Honey Candy",
	 HoneyCrepe: "Honey Crepe",
	 HoneyedApple: "Honeyed Apple",
	 HoneyedFruits: "Honeyed Fruits",
	 HotButteredApple: "Hot Buttered Apple",
	 HotFootedFrog: "Hot-Footed Frog",
	 Hydromelon: "Hydromelon",
	 HylianBass: "Hylian Bass",
	 HylianMushroom: "Hylian Mushroom",
	 HylianRice: "Hylian Rice",
	 HyruleHerb: "Hyrule Herb",
	 IceKeeseWing: "Ice Keese Wing",
	 IcyGourmetMeat: "Icy Gourmet Meat",
	 IcyHeartyBlueshellSnail: "Icy Hearty Blueshell Snail",
	 IcyLizalfosTail: "Icy Lizalfos Tail",
	 IcyMeat: "Icy Meat",
	 IcyPrimeMeat: "Icy Prime Meat",
	 IronshellCrab: "Ironshell Crab",
	 Ironshroom: "Ironshroom",
	 KeeseEyeball: "Keese Eyeball",
	 KeeseWing: "Keese Wing",
	 LizalfosHorn: "Lizalfos Horn",
	 LizalfosTail: "Lizalfos Tail",
	 LizalfosTalon: "Lizalfos Talon",
	 LuminousStone: "Luminous Stone",
	 LynelGuts: "Lynel Guts",
	 LynelHoof: "Lynel Hoof",
	 LynelHorn: "Lynel Horn",
	 MeatCurry: "Meat Curry",
	 MeatPie: "Meat Pie",
	 MeatSkewer: "Meat Skewer",
	 MeatStew: "Meat Stew",
	 MeatStuffedPumpkin: "Meat-Stuffed Pumpkin",
	 MeatandMushroomSkewer: "Meat and Mushroom Skewer",
	 MeatandRiceBowl: "Meat and Rice Bowl",
	 MeatandSeafoodFry: "Meat and Seafood Fry",
	 MeatyRiceBalls: "Meaty Rice Balls",
	 MightyBananas: "Mighty Bananas",
	 MightyCarp: "Mighty Carp",
	 MightyPorgy: "Mighty Porgy",
	 MightyThistle: "Mighty Thistle",
	 Milk: "Milk",
	 MoblinFang: "Moblin Fang",
	 MoblinGuts: "Moblin Guts",
	 MoblinHorn: "Moblin Horn",
	 MoldugaFin: "Molduga Fin",
	 MoldugaGuts: "Molduga Guts",
	 MonsterCake: "Monster Cake",
	 MonsterCurry: "Monster Curry",
	 MonsterExtract: "Monster Extract",
	 MonsterRiceBalls: "Monster Rice Balls",
	 MonsterSoup: "Monster Soup",
	 MonsterStew: "Monster Stew",
	 MushroomOmelet: "Mushroom Omelet",
	 MushroomRiceBalls: "Mushroom Rice Balls",
	 MushroomRisotto: "Mushroom Risotto",
	 MushroomSkewer: "Mushroom Skewer",
	 Nutcake: "Nutcake",
	 NyadrasClaw: "Nyadra's Claw",
	 NyadrasScale: "Nyadra's Scale",
	 OctoBalloon: "Octo Balloon",
	 OctorokEyeball: "Octorok Eyeball",
	 OctorokTentacle: "Octorok Tentacle",
	 Omelet: "Omelet",
	 Opal: "Opal",
	 PalmFruit: "Palm Fruit",
	 PepperSeafood: "Pepper Seafood",
	 PepperSteak: "Pepper Steak",
	 PlainCrepe: "Plain Crepe",
	 PorgyMeunière: "Porgy Meunière",
	 PoultryCurry: "Poultry Curry",
	 PoultryPilaf: "Poultry Pilaf",
	 PrimeMeatCurry: "Prime Meat Curry",
	 PrimeMeatStew: "Prime Meat Stew",
	 PrimeMeatandRiceBowl: "Prime Meat and Rice Bowl",
	 PrimeMeatandSeafoodFry: "Prime Meat and Seafood Fry",
	 PrimePoultryCurry: "Prime Poultry Curry",
	 PrimePoultryPilaf: "Prime Poultry Pilaf",
	 PrimeSpicedMeatSkewer: "Prime Spiced Meat Skewer",
	 PumpkinPie: "Pumpkin Pie",
	 PumpkinStew: "Pumpkin Stew",
	 RawBirdDrumstick: "Raw Bird Drumstick",
	 RawBirdThigh: "Raw Bird Thigh",
	 RawGourmetMeat: "Raw Gourmet Meat",
	 RawMeat: "Raw Meat",
	 RawPrimeMeat: "Raw Prime Meat",
	 RawWholeBird: "Raw Whole Bird",
	 RazorclawCrab: "Razorclaw Crab",
	 Razorshroom: "Razorshroom",
	 RedChuchuJelly: "Red Chuchu Jelly",
	 RedLizalfosTail: "Red Lizalfos Tail",
	 RestlessCricket: "Restless Cricket",
	 RoastedAcorn: "Roasted Acorn",
	 RoastedArmoranth: "Roasted Armoranth",
	 RoastedBass: "Roasted Bass",
	 RoastedBigRadish: "Roasted Big Radish",
	 RoastedBirdDrumstick: "Roasted Bird Drumstick",
	 RoastedBirdThigh: "Roasted Bird Thigh",
	 RoastedCarp: "Roasted Carp",
	 RoastedEnduraCarrot: "Roasted Endura Carrot",
	 RoastedHeartyBass: "Roasted Hearty Bass",
	 RoastedHeartyDurian: "Roasted Hearty Durian",
	 RoastedHeartySalmon: "Roasted Hearty Salmon",
	 RoastedHydromelon: "Roasted Hydromelon",
	 RoastedLotusSeed: "Roasted Lotus Seed",
	 RoastedMightyBananas: "Roasted Mighty Bananas",
	 RoastedMightyThistle: "Roasted Mighty Thistle",
	 RoastedPorgy: "Roasted Porgy",
	 RoastedRadish: "Roasted Radish",
	 RoastedSwiftCarrot: "Roasted Swift Carrot",
	 RoastedTreeNut: "Roasted Tree Nut",
	 RoastedTrout: "Roasted Trout",
	 RoastedVoltfruit: "Roasted Voltfruit",
	 RoastedWholeBird: "Roasted Whole Bird",
	 RoastedWildberry: "Roasted Wildberry",
	 RockHardFood: "Rock-Hard Food",
	 RockSalt: "Rock Salt",
	 Ruby: "Ruby",
	 RuggedRhinoBeetle: "Rugged Rhino Beetle",
	 Rushroom: "Rushroom",
	 SalmonMeunière: "Salmon Meunière",
	 SalmonRisotto: "Salmon Risotto",
	 SaltGrilledCrab: "Salt-Grilled Crab",
	 SaltGrilledFish: "Salt-Grilled Fish",
	 SaltGrilledGourmetMeat: "Salt-Grilled Gourmet Meat",
	 SaltGrilledGreens: "Salt-Grilled Greens",
	 SaltGrilledMeat: "Salt-Grilled Meat",
	 SaltGrilledMushrooms: "Salt-Grilled Mushrooms",
	 SaltGrilledPrimeMeat: "Salt-Grilled Prime Meat",
	 SankeCarp: "Sanke Carp",
	 Sapphire: "Sapphire",
	 SautéedNuts: "Sautéed Nuts",
	 SautéedPeppers: "Sautéed Peppers",
	 SeafoodCurry: "Seafood Curry",
	 SeafoodFriedRice: "Seafood Fried Rice",
	 SeafoodMeunière: "Seafood Meunière",
	 SeafoodPaella: "Seafood Paella",
	 SeafoodRiceBalls: "Seafood Rice Balls",
	 SeafoodSkewers: "Seafood Skewers",
	 SearedGourmetSteak: "Seared Gourmet Steak",
	 SearedPrimeSteak: "Seared Prime Steak",
	 SearedSteak: "Seared Steak",
	 ShardofDinraalsFang: "Shard of Dinraal's Fang",
	 ShardofDinraalsHorn: "Shard of Dinraal's Horn",
	 ShardofFaroshsFang: "Shard of Farosh's Fang",
	 ShardofFaroshsHorn: "Shard of Farosh's Horn",
	 ShardofNyadrasFang: "Shard of Nyadra's Fang",
	 ShardofNyadrasHorn: "Shard of Nyadra's Horn",
	 SilentPrincess: "Silent Princess",
	 SilentShroom: "Silent Shroom",
	 SimmeredFruits: "Simmered Fruits",
	 SizzlefinTrout: "Sizzlefin Trout",
	 SmotherwingButterfly: "Smotherwing Butterfly",
	 SneakyRiverEscargot: "Sneaky River Escargot",
	 SneakyRiverSnail: "Sneaky River Snail",
	 SpicedMeatSkewer: " Spiced Meat Skewer",
	 SpicyPepper: "Spicy Pepper",
	 StamellaMushroom: "Stamella Mushroom",
	 StaminokaBass: "Staminoka Bass",
	 StarFragment: "Star Fragment",
	 StealthfinTrout: "Stealthfin Trout",
	 SteamedFish: "Steamed Fish",
	 SteamedFruit: "Steamed Fruit",
	 SteamedMeat: "Steamed Meat",
	 SteamedMushrooms: "Steamed Mushrooms",
	 SummerwingButterfly: "Summerwing Butterfly",
	 SunsetFirefly: "Sunset Firefly",
	 Sunshroom: "Sunshroom",
	 SwiftCarrot: "Swift Carrot",
	 SwiftViolet: "Swift Violet",
	 TabanthaWheat: "Tabantha Wheat",
	 ThunderwingButterfly: "Thunderwing Butterfly",
	 TirelessFrog: "Tireless Frog",
	 ToastedBigHeartTruffle: "Toasted Big Heart Truffle",
	 ToastedHeartyTruffle: "Toasted Hearty Truffle",
	 ToastyChillshroom: "Toasty Chillshroom",
	 ToastyEnduraShroom: "Toasty Endura Shroom",
	 ToastyHylianShroom: "Toasty Hylian Shroom",
	 ToastyIronshroom: "Toasty Ironshroom",
	 ToastyRazorshroom: "Toasty Razorshroom",
	 ToastyRushroom: "Toasty Rushroom",
	 ToastySilentShroom: "Toasty Silent Shroom",
	 ToastyStamellaShroom: "Toasty Stamella Shroom",
	 ToastySunshroom: "Toasty Sunshroom",
	 ToastyZapshroom: "Toasty Zapshroom",
	 Topaz: "Topaz",
	 VegetableCurry: "Vegetable Curry",
	 VegetableOmelet: "Vegetable Omelet",
	 VegetableRisotto: "Vegetable Risotto",
	 VeggieCreamSoup: "Veggie Cream Soup",
	 VeggieRiceBalls: "Veggie Rice Balls",
	 VoltfinTrout: "Voltfin Trout",
	 Voltfruit: "Voltfruit",
	 WarmDarner: "Warm Darner",
	 WarmSafflina: "Warm Safflina",
	 WheatBread: "Wheat Bread",
	 WhiteChuchuJelly: "White Chuchu Jelly",
	 Wildberry: "Wildberry",
	 WildberryCrepe: "Wildberry Crepe",
	 WinterwingButterfly: "Winterwing Butterfly",
	 Wood: "Wood",
	 YellowChuchuJelly: "Yellow Chuchu Jelly",
	 YellowLizalfosTail: "Yellow Lizalfos Tail",
	 Zapshroom: "Zapshroom",
	}

export interface SpriteLoc{
	X: number;
	Y: number;
}

export var Sprites: {[id: string]: SpriteLoc} = {
	 "Acorn": {X: 18, Y: 28},
	 "Amber": {X: 0, Y: 0},
	 "Ancient Core": {X: 0, Y: 0},
	 "Ancient Gear": {X: 0, Y: 0},
	 "Ancient Screw": {X: 0, Y: 0},
	 "Ancient Shaft": {X: 0, Y: 0},
	 "Ancient Spring": {X: 0, Y: 0},
	 "Apple": {X: 7, Y: 28},
	 "Armoranth": {X: 31, Y: 29},
	 "Armored Carp": {X: 37, Y: 27},
	 "Armored Porgy": {X: 36, Y: 27},
	 "Big Hearty Radish": {X: 27, Y: 29},
	 "Big Hearty Truffle": {X: 11, Y: 29},
	 "Bird Egg": {X: 26, Y: 28},
	 "Bladed Rhino Beetle": {X: 8, Y: 0},
	 "Blue Nightshade": {X: 32, Y: 29},
	 "Bokoblin Fang": {X: 0, Y: 0},
	 "Bokoblin Guts": {X: 0, Y: 0},
	 "Bokoblin Horn": {X: 0, Y: 0},
	 "Bright-Eyed Crab": {X: 22, Y: 28},
	 "Cane Sugar": {X: 23, Y: 28},
	 "Chickaloo Tree Nut": {X: 19, Y: 28},
	 "Chillfin Trout": {X: 32, Y: 27},
	 "Chillshroom": {X: 1, Y: 29},
	 "Chuchu Jelly": {X: 0, Y: 0},
	 "Cold Darner": {X: 5, Y: 0},
	 "Cool Safflina": {X: 28, Y: 29},
	 "Courser Bee Honey": {X: 15, Y: 21},
	 "Diamond": {X: 0, Y: 0},
	 "Dinraal's Claw": {X: 0, Y: 0},
	 "Dinraal's Scale": {X: 0, Y: 0},
	 "Electric Darner": {X: 10, Y: 0},
	 "Electric Keese Wing": {X: 0, Y: 0},
	 "Electric Safflina": {X: 34, Y: 29},
	 "Endura Carrot": {X: 37, Y: 29},
	 "Endura Shroom": {X: 13, Y: 29},
	 "Energetic Rhino Beetle": {X: 2, Y: 0},
	 "Fairy": {X: 7, Y: 0},
	 "Farosh's Claw": {X: 0, Y: 0},
	 "Farosh's Scale": {X: 0, Y: 0},
	 "Fire Keese Wing": {X: 0, Y: 0},
	 "Fireproof Lizard": {X: 20, Y: 0},
	 "Fleet-Lotus Seeds": {X: 12, Y: 28},
	 "Flint": {X: 0, Y: 0},
	 "Fortified Pumpkin": {X: 17, Y: 28},
	 "Fresh Milk": {X: 27, Y: 28},
	 "Giant Ancient Core": {X: 0, Y: 0},
	 "Goat Butter": {X: 29, Y: 28},
	 "Goron Spice": {X: 24, Y: 28},
	 "Hearty Bass": {X: 31, Y: 27},
	 "Hearty Blueshell Snail": {X: 1, Y: 28},
	 "Hearty Durian": {X: 10, Y: 28},
	 "Hearty Lizard": {X: 12, Y: 0},
	 "Hearty Radish": {X: 26, Y: 29},
	 "Hearty Salmon": {X: 38, Y: 27},
	 "Hearty Truffle": {X: 5, Y: 29},
	 "Hightail Lizard": {X: 18, Y: 0},
	 "Hinox Guts": {X: 0, Y: 0},
	 "Hinox Toenail": {X: 0, Y: 0},
	 "Hinox Tooth": {X: 0, Y: 0},
	 "Hot-Footed Frog": {X: 1, Y: 0},
	 "Hydromelon": {X: 13, Y: 28},
	 "Hylian Bass": {X: 30, Y: 27},
	 "Hylian Mushroom": {X: 4, Y: 29},
	 "Hylian Rice": {X: 25, Y: 28},
	 "Hyrule Herb": {X: 25, Y: 29},
	 "Ice Keese Wing": {X: 0, Y: 0},
	 "Icy Lizalfos Tail": {X: 0, Y: 0},
	 "Ironshell Crab": {X: 21, Y: 28},
	 "Ironshroom": {X: 10, Y: 29},
	 "Keese Eyeball": {X: 0, Y: 0},
	 "Keese Wing": {X: 0, Y: 0},
	 "Lizalfos Horn": {X: 0, Y: 0},
	 "Lizalfos Tail": {X: 0, Y: 0},
	 "Lizalfos Talon": {X: 0, Y: 0},
	 "Luminous Stone": {X: 0, Y: 0},
	 "Lynel Guts": {X: 0, Y: 0},
	 "Lynel Hoof": {X: 0, Y: 0},
	 "Lynel Horn": {X: 0, Y: 0},
	 "Mighty Bananas": {X: 15, Y: 28},
	 "Mighty Carp": {X: 34, Y: 27},
	 "Mighty Porgy": {X: 35, Y: 27},
	 "Mighty Thistle": {X: 30, Y: 29},
	 "Moblin Fang": {X: 0, Y: 0},
	 "Moblin Guts": {X: 0, Y: 0},
	 "Moblin Horn": {X: 0, Y: 0},
	 "Molduga Fin": {X: 0, Y: 0},
	 "Molduga Guts": {X: 0, Y: 0},
	 "Monster Extract": {X: 31, Y: 28},
	 "Nyadra's Claw": {X: 0, Y: 0},
	 "Nyadra's Scale": {X: 0, Y: 0},
	 "Octo Balloon": {X: 0, Y: 0},
	 "Octorok Eyeball": {X: 0, Y: 0},
	 "Octorok Tentacle": {X: 0, Y: 0},
	 "Opal": {X: 0, Y: 0},
	 "Palm Fruit": {X: 14, Y: 28},
	 "Raw Bird Drumstick": {X: 34, Y: 28},
	 "Raw Bird Thigh": {X: 35, Y: 28},
	 "Raw Gourmet Meat": {X: 36, Y: 28},
	 "Raw Meat": {X: 34, Y: 28},
	 "Raw Prime Meat": {X: 33, Y: 28},
	 "Raw Whole Bird": {X: 37, Y: 28},
	 "Razorclaw Crab": {X: 20, Y: 28},
	 "Razorshroom": {X: 9, Y: 29},
	 "Red Chuchu Jelly": {X: 0, Y: 0},
	 "Red Lizalfos Tail": {X: 0, Y: 0},
	 "Restless Cricket": {X: 9, Y: 0},
	 "Rock Salt": {X: 22, Y: 29},
	 "Ruby": {X: 0, Y: 0},
	 "Rugged Rhino Beetle": {X: 15, Y: 0},
	 "Rushroom": {X: 38, Y: 28},
	 "Sanke Carp": {X: 6, Y: 28},
	 "Sapphire": {X: 0, Y: 0},
	 "Shard of Dinraal's Fang": {X: 0, Y: 0},
	 "Shard of Dinraal's Horn": {X: 0, Y: 0},
	 "Shard of Farosh's Fang": {X: 0, Y: 0},
	 "Shard of Farosh's Horn": {X: 0, Y: 0},
	 "Shard of Nyadra's Fang": {X: 0, Y: 0},
	 "Shard of Nyadra's Horn": {X: 0, Y: 0},
	 "Silent Princess": {X: 33, Y: 29},
	 "Silent Shroom": {X: 8, Y: 29},
	 "Sizzlefin Trout": {X: 0, Y: 28},
	 "Smotherwing Butterfly": {X: 3, Y: 0},
	 "Sneaky River Snail": {X: 4, Y: 28},
	 "Spicy Pepper": {X: 16, Y: 28},
	 "Stamella Mushroom": {X: 0, Y: 29},
	 "Staminoka Bass": {X: 2, Y: 28},
	 "Star Fragment": {X: 0, Y: 0},
	 "Stealthfin Trout": {X: 5, Y: 28},
	 "Summerwing Butterfly": {X: 16, Y: 0},
	 "Sunset Firefly": {X: 6, Y: 0},
	 "Sunshroom": {X: 2, Y: 29},
	 "Swift Carrot": {X: 35, Y: 29},
	 "Swift Violet": {X: 36, Y: 29},
	 "Tabantha Wheat": {X: 30, Y: 28},
	 "Thunderwing Butterfly": {X: 17, Y: 0},
	 "Tireless Frog": {X: 4, Y: 0},
	 "Topaz": {X: 0, Y: 0},
	 "Voltfin Trout": {X: 33, Y: 27},
	 "Voltfruit": {X: 21, Y: 28},
	 "Warm Darner": {X: 19, Y: 0},
	 "Warm Safflina": {X: 29, Y: 29},
	 "White Chuchu Jelly": {X: 0, Y: 0},
	 "Wildberry": {X: 8, Y: 28},
	 "Winterwing Butterfly": {X: 13, Y: 0},
	 "Wood": {X: 0, Y: 0},
	 "Yellow Chuchu Jelly": {X: 0, Y: 0},
	 "Yellow Lizalfos Tail": {X: 0, Y: 0},
	 "Zapshroom": {X: 7, Y: 29},
	}
